const KEY="nogekiri_v2";
const defaults={currentAge:20,targetAge:35,currentAssets:1000000,annualReturn:7,jobRoute:"カスタム",income20early:1000000,income20late:5000000,income30early:9000000,income30late:12000000,income40plus:15000000,taxMode:"auto",manualTakeHomeRate:74,expenseMode:"manual",monthlyLivingCost:300000,rent:80000,fixedCost:50000,hobbyCost:70000,annualSpecial:300000,investMode:"auto",manualInvestment:150000,sideIncome:0,sideGrowth:30,sideCap:300000,sideTakeHomeRate:80,dailyTakeHome:30000,acceptableDays:3,selectedPhase:"20代前半"};
const phases=[["20代前半","income20early"],["20代後半","income20late"],["30代前半","income30early"],["30代後半","income30late"],["40代以降","income40plus"]];
const routes={"会社員":{manualTakeHomeRate:75},"医師":{manualTakeHomeRate:63},"エンジニア":{manualTakeHomeRate:72},"資格職":{manualTakeHomeRate:70},"公務員":{manualTakeHomeRate:76},"起業・副業":{manualTakeHomeRate:68},"学生":{manualTakeHomeRate:90},"カスタム":{}};
const ids=Object.keys(defaults), state={...defaults,...JSON.parse(localStorage.getItem(KEY)||"{}")}, charts={};
const el=id=>document.getElementById(id), yen=v=>`¥${Math.round(v).toLocaleString("ja-JP")}`;
function takeRate(income,s){if(s.taxMode==="manual")return s.manualTakeHomeRate/100; if(income<3000000)return .82;if(income<5000000)return .78;if(income<8000000)return .74;if(income<12000000)return .69;if(income<18000000)return .63;return .58;}
function incomeByAge(age,s){if(age<25)return s.income20early;if(age<30)return s.income20late;if(age<35)return s.income30early;if(age<40)return s.income30late;return s.income40plus;}
function buildBanners(){const wrap=el("incomeBanners"); wrap.innerHTML=phases.map(([n,k])=>{const active=state.selectedPhase===n?"active":"";const inc=Number(state[k]);const tr=Math.round(takeRate(inc,state)*100);return `<button class="income-banner ${active}" data-phase="${n}"><strong>${n}</strong><div>年収 ${yen(inc)}</div><div>推定手取り率 ${tr}%</div></button>`}).join("");
 wrap.querySelectorAll("button").forEach(b=>b.onclick=()=>{state.selectedPhase=b.dataset.phase;save();updateTaxAndDaily();buildBanners();render();});}
function collect(){ids.forEach(i=>{const n=el(i).type==="number"?Number(el(i).value):el(i).value;state[i]=n;}); save(); return state;}
function save(){localStorage.setItem(KEY,JSON.stringify(state));}
function getMonthlyCost(s){return s.expenseMode==="auto"?(s.rent+s.fixedCost+s.hobbyCost+s.annualSpecial/12):s.monthlyLivingCost;}
function updateTaxAndDaily(){const key=phases.find(p=>p[0]===state.selectedPhase)?.[1]||"income20early";const annual=Number(state[key]);const tr=takeRate(annual,state); if(state.taxMode==="auto")el("manualTakeHomeRate").value=Math.round(tr*100);
 const daily=(annual*tr)/240; state.dailyTakeHome=Math.max(Math.round(daily),1); el("dailyTakeHome").value=state.dailyTakeHome;
 el("dailyHint").textContent=`選択年収 ${yen(annual)} の推定手取りから、1日あたり手取りを ${yen(state.dailyTakeHome)} として自動計算しています（年間240労働日換算）。`;
 const mc=getMonthlyCost(state); el("expenseSummary").textContent=`現在の月生活費は ${yen(mc)} です。${state.expenseMode==="auto"?"（内訳から自動計算）":"（直接入力）"}`; save();}
function calc(customReturn,sin){const s=sin||collect(); const arr=[]; let assets=s.currentAssets, side=s.sideIncome; let e5,e3,e1,fire;
 for(let age=s.currentAge;age<=Math.max(s.targetAge,60);age++){const annual=incomeByAge(age,s),tr=takeRate(annual,s),take=annual*tr,monthTake=take/12,monthlyCost=getMonthlyCost(s),invest=s.investMode==="manual"?s.manualInvestment:Math.max(monthTake-monthlyCost,0); side=Math.min(side*(1+s.sideGrowth/100),s.sideCap); const sideNet=side*(s.sideTakeHomeRate/100),assetIncome=assets*.04/12,escape=((assetIncome+sideNet)/monthlyCost)*100,shortage=Math.max(monthlyCost-assetIncome-sideNet,0),needWeek=(shortage/s.dailyTakeHome)/4;
 if(e5===undefined&&needWeek<=5)e5=age;if(e3===undefined&&needWeek<=3)e3=age;if(e1===undefined&&needWeek<=1)e1=age;if(fire===undefined&&shortage<=0)fire=age;
 arr.push({age,annual,take,monthlyCost,invest,assets,assetIncome,sideNet,escape,needWeek,taxLoss:annual-take}); assets=assets*(1+(customReturn??s.annualReturn)/100)+invest*12; if(age===30)assets*=.7;if(age===33)assets*=.5;}
 return {arr,e5,e3,e1,fire,s};}
function score(r){return Math.round((Math.min(r.escape,180)/1.8+Math.max(0,100-r.needWeek*20)+Math.min(r.assets/50000000*100,100)+Math.min(r.sideNet/200000*100,100)+Math.min(r.invest/200000*100,100)+Math.min((r.assets/(r.monthlyCost*12))*5,100))/6)}
function rank(sc){if(sc>=85)return"S";if(sc>=75)return"A";if(sc>=60)return"B";if(sc>=45)return"C";if(sc>=30)return"D";return"E"}
function mk(id,type,labels,datasets){charts[id]?.destroy();charts[id]=new Chart(el(id),{type,data:{labels,datasets},options:{responsive:true,maintainAspectRatio:false}})}
function draw(res){const L=res.arr.map(v=>v.age),D=res.arr;mk("assetChart","line",L,[{label:"予想資産額",data:D.map(v=>v.assets),borderColor:"#0f766e"}]);mk("incomeChart","line",L,[{label:"年収",data:D.map(v=>v.annual),borderColor:"#2563eb"},{label:"手取り",data:D.map(v=>v.take),borderColor:"#16a34a"}]);mk("investChart","bar",L,[{label:"毎月投資可能額",data:D.map(v=>v.invest),backgroundColor:"#0ea5e9"}]);mk("escapeChart","line",L,[{label:"労働脱出率(%)",data:D.map(v=>v.escape),borderColor:"#22c55e"}]);const t=D.find(v=>v.age===res.s.targetAge)??D.at(-1),labor=Math.max(t.monthlyCost-t.assetIncome-t.sideNet,0);mk("ratioChart","doughnut",["資産収入","副業手取り","労働収入"],[{data:[t.assetIncome,t.sideNet,labor],backgroundColor:["#14b8a6","#3b82f6","#64748b"]}]);mk("scenarioChart","line",L,[{label:"3%",data:calc(3,res.s).arr.map(v=>v.assets),borderColor:"#94a3b8"},{label:"5%",data:calc(5,res.s).arr.map(v=>v.assets),borderColor:"#22c55e"},{label:"7%",data:calc(7,res.s).arr.map(v=>v.assets),borderColor:"#0ea5e9"},{label:"10%",data:calc(10,res.s).arr.map(v=>v.assets),borderColor:"#7c3aed"}]);}
function render(){updateTaxAndDaily(); const res=calc(); const target=res.arr.find(x=>x.age===res.s.targetAge)??res.arr.at(-1), sc=score(target), r=rank(sc); el("score").textContent=`${sc}点 (${r})`;el("escape5").textContent=res.e5??"未到達";el("fireAge").textContent=res.fire??"未到達";const no=calc(null,{...res.s,sideIncome:0}); const fast=(no.e5??999)-(res.e5??999);
 el("resultText").innerHTML=`<h2>診断結果</h2><ul><li>目標年齢の必要労働日数: ${target.needWeek.toFixed(2)}日/週</li><li>副業月${Math.round(res.s.sideIncome/10000)}万円は、週5脱出を${fast>0?fast.toFixed(1):0}年早めます。</li><li>税・社保で年間 ${yen(target.taxLoss)} が消える想定です。</li><li>年収${yen(target.annual)} → 手取り約${yen(target.take)}。</li></ul>`; draw(res);}
function init(){Object.keys(routes).forEach(k=>el("jobRoute").add(new Option(k,k))); ids.forEach(i=>el(i).value=state[i]); buildBanners();
 el("jobRoute").onchange=()=>{Object.entries(routes[el("jobRoute").value]||{}).forEach(([k,v])=>el(k).value=v);collect();render();};
 document.querySelectorAll("input,select").forEach(n=>n.addEventListener("change",()=>{collect();buildBanners();render();})); el("calcBtn").onclick=render; render();}
init();
